name: TAMULib Sage Maven Cache

on: [ workflow_dispatch ]

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Cache Maven Dependencies"
        uses: actions/cache@v2
        env:
          cache-name: sage-cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-sage-cache-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-sage-cache-maven-${{ hashFiles('**/pom.xml') }}

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: "Fixing node_modules Path for Java"
        run: sudo chown $RUNNER_USER /usr/local/lib/node_modules/

      - name: "Loading Maven Dependencies"
        run: mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
