name: TAMULib Sage Coveralls Matrix

on:
  push:
    branches:
      - $default_branch
      - sprint*-staging

  pull_request:

  workflow_dispatch:

jobs:
  coveralls:
    runs-on: ubuntu-latest


    # Setup Matrix
    strategy:
      max-parallel: 2
      matrix:
        language_engine:
          - java
          - node

        include:
          - language_engine: java
            version: 1.8

          - language_engine: node
            version: 12


    # Checkout Repository Code
    steps:
      - uses: actions/checkout@v2


      # Setup Caches
      - name: "Cache Java Maven Dependencies"
        if: ${{ matrix.language_engine == 'java' }}
        uses: actions/cache@v2
        env:
          cache-name: sage-cache-maven-dependencies
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-sage-cache-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-sage-cache-maven-${{ hashFiles('**/pom.xml') }}

      - name: "Cache Node Dependencies"
        if: ${{ matrix.language_engine == 'node' }}
        uses: actions/cache@v2
        env:
          cache-name: sage-cache-node-dependencies
        with:
          path: ~/.npm
          key: ${{ runner.os }}-sage-cache-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-sage-cache-node-${{ hashFiles('**/package.json', '**/package-lock.json') }}


      # Setup Java and Node
      - name: "Setup Java"
        if: ${{ matrix.language_engine == 'java' }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}

      - name: "Setup Node"
        if: ${{ matrix.language_engine == 'node' }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      - name: "Install Node Dependencies"
        if: ${{ matrix.language_engine == 'node' }}
        run: npm install


      # Run Tests
      - name: "Fixing node_modules Path for Java"
        if: ${{ matrix.language_engine == 'java' }}
        run: sudo chown $RUNNER_USER /usr/local/lib/node_modules/

      - name: "Compiling Tests for Java"
        if: ${{ matrix.language_engine == 'java' }}
        run: mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: "Running Tests for Java"
        if: ${{ matrix.language_engine == 'java' }}
        run: mvn clean test cobertura:cobertura jacoco:report coveralls:report -DdryRun=true

      - name: "Starting Service for Node"
        if: ${{ matrix.language_engine == 'node' }}
        run: |
          npm start > /dev/null &
          npm run update-webdriver
          sleep 1 # give server time to start

      - name: "Pre-processing Tests for Node"
        if: ${{ matrix.language_engine == 'node' }}
        run: grunt coverage-preprocess

      - name: "Running Tests for Node"
        if: ${{ matrix.language_engine == 'node' }}
        env:
          COVERALLS_BUILD_NUMBER: sage-${{ github.action }}-${{ github.run_number }}-${{ matrix.language_engine }}
          COVERALLS_REPO_TOKEN: ${{ secrets.coveralls_repo_token }}
          COVERALLS_PARALLEL: true
        run: |
          npm run test-ci
          grunt coverage
          mv ./src/main/webapp/coverage/*/* ./src/main/webapp/coverage/ # move coverage data outside of the browser specific path.


      # Initiate Coveralls
      - name: "To Coveralls Java (build sage-sage-${{ github.action }}-${{ github.run_number }}-${{ matrix.language_engine }})"
        if: ${{ matrix.language_engine == 'java' }}
        uses: MikeEdgar/github-action@raw_coverage_file
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: sage-${{ github.action }}-${{ github.run_number }}-${{ matrix.language_engine }}
          parallel: true
          path-to-file: ./target/coveralls.json
          coverage-format: raw

      - name: "To Coveralls Node (build sage-${{ github.action }}-${{ github.run_number }}-${{ matrix.language_engine }})"
        if: ${{ matrix.language_engine == 'node' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: sage-${{ github.action }}-${{ github.run_number }}-${{ matrix.language_engine }}
          parallel: true
          path-to-lcov: './src/main/webapp/coverage/lcov.info'


  # Resolve Coveralls Parallel
  finish:
    needs: coveralls
    runs-on: ubuntu-latest

    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
